### ISSUE TITLE
Accept interface{} argument in Logger.Info() and Logger.Debug()

### ISSUE THREAD

**Issue by aaron0browne** [arcus/pkg#13]
As it stands right now, I'm logging errors with `logger.Info(err.Error())`. I'm totally in favor of the "only-two-levels" theory of logging, but it would be nice if the client code did not have to call `err.Error()` every time and this was handled by the logger code. So this could either be a separate method on `Logger` as I'm suggesting, or a type switch in the `Info` method.

**Comment by bruth** [comment]
Sure that would be a nice improvement. If the `Info` and `Debug` methods take and `interface{}` value, then it could handle this case. Adding and `Err` method would be fine as well as long as it is documented that this is a convenience and does not represent an error level log.

**Comment by bruth** [comment]
I do. It can handle `io.Stringer` cases transparently as well.

**Comment by aaron0browne** [comment]
Agreed!
