### ISSUE TITLE
Arcus context fields and event metadata

### ISSUE THREAD

**Issue by bruth** [arcus/pkg#4]
Currently the `arcus.Context` type has fields `AccessToken`, `UserID`, and `UserRole`. I had defined an [`EventMetadata` type](https://github.com/arcus/iam/blob/master/api/v1/api.proto#L143-L155) to be serialized with an `eventual.Event` that has a mix of fields as well. The purpose of this issue to review the fields we have available in context and want to include in the event metadata as well as standardize on names for future proofing (hence the *principle* rather than *user* term).

**Comment by aaron0browne** [comment]
It seems like the only two changes we need are to rename the field on `arcus.Context` to `PrincipalID` and add the role to the event metadata type? The role attribute could be named `PrincipalRole` in both places to match the ID.

Oh, and I'm unclear on which code base `code_version` refers to. What was your intention for that?

**Comment by aaron0browne** [comment]
We could also move the message definition to this code base and even rename it to `Context`... In fact, the `arcus.Context` could just be a wrapper around the message, right?

**Comment by bruth** [comment]
Yes changing to `Principle*` would be a good start, but wanted everyone to think about any other fields that may be valuable up front. If not, then we can move forward until we discover something.

**Comment by bruth** [comment]
To answer your second question, yes I think the event metadata type should be moved here. Renaming to `Context` is fine.

**Comment by aaron0browne** [comment]
What about `code_version`? What are the semantics of that? Are you expecting something specific, like a commit hash, and if so, then from which component? Or just like a `v1`? I think we should just move forward with what we've got and change when/if we need to.

**Comment by aaron0browne** [comment]
OK, cool! I'll move the message definition and rename as we've discussed.

**Comment by aaron0browne** [comment]
Fixed in #3
