### ISSUE TITLE
[transport/http] Register POST method route for query operations

### ISSUE THREAD

**Issue by bruth** [arcus/pkg#7]
The HTTP transport methods assume a query uses the GET method and a command uses the POST method. The problem is that if a query requires a request body that cannot be easily (or at all) encoded as GET parameters, then this abstraction breaks down. Per the HTTP spec, the semantics of POST aren't actually defined.. meaning it is not tied to resource creation specifically.. that is just what it is most often used for in a REST context. But it can be used for operations that require a request body. The obnoxious thing is that the spec doesn't disallow request bodies in a GET request, but barely any tooling or servers support this.. so its basically not supported.

@aaron0browne Rather than making this another option or API, what do you think about just adding another route bound to the POST method for queries?

**Comment by bruth** [comment]
Hrm. I see that `Query` and `Command` returns a `*Route` so that wouldn't work if two routes are registered. Maybe `QueryBody` should just be added to differentiate.

**Comment by aaron0browne** [comment]
It sounds like what you're saying is that the difference between a `Query` and a `Command` is not well articulated in HTTP transport, so maybe we should replace them with a single `Route` method that always uses POST?

**Comment by bruth** [comment]
> maybe we should replace them with a single Route method that always uses POST?

Sure that is a good option. gRPC [standardizes on](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests) a HTTP/2 POST for all requests.

GET params are nice and convenient at times for handing crafting requests for cURL, but certainly not necessary for programmatic access.

**Comment by bruth** [comment]
This can be done explicitly now per #11.
